kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: syncthing-data
#  annotations:
#    volume.beta.kubernetes.io/storage-class: openebs-standalone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
