apiVersion: v1
kind: Service
metadata:
  name: sync-prod
  labels:
    app: sync-prod
spec:
  ports:
  - port: 18384
    name: sync
  selector:
    app: sync-prod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sync
spec:
  selector:
    matchLabels:
      app: sync-prod # has to match .spec.template.metadata.labels
  serviceName: "sync-prod"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: sync-prod # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: linuxserver/syncthing
        name: syncthing
        resources: {}
        volumeMounts:
        - name: sync
          mountPath: "/config"
  volumeClaimTemplates:
  - metadata:
      name: sync
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "rbd"
      resources:
        requests:
          storage: 1Gi